# Generated by Django 6.0.4 on 2026-04-25 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('category', models.CharField(choices=[('Conference', 'conference'), ('Workshop', 'workshop'), ('Webinar', 'webinar'), ('Networking', 'networking'), ('Seminar', 'seminar')], max_length=50)),
                ('event_type', models.CharField(choices=[('In-Person', 'in-Person'), ('Virtual', 'virtual'), ('Hybrid', 'hybrid')], max_length=20)),
                ('organizer_name', models.CharField(max_length=200)),
                ('organizer_email', models.EmailField(max_length=254)),
                ('organizer_phone', models.CharField(max_length=15)),
                ('venue_name', models.CharField(blank=True, max_length=200)),
                ('venue_address', models.TextField(blank=True)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('max_attendees', models.IntegerField()),
                ('banner_image_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'draft'), ('Published', 'published'), ('Cancelled', 'cancelled'), ('Completed', 'completed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('attended', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendees.attendee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'unique_together': {('event', 'attendee')},
            },
        ),
    ]
