# Generated by Django 6.0.4 on 2026-05-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='attendee_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
