# Generated by Django 6.0.4 on 2026-05-01 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0002_alter_attendee_attendee_id'),
        ('events', '0003_event_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='events.event'),
        ),
    ]
